//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayInfoHelper.MSSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ajuma_devEntities : DbContext
    {
        public Ajuma_devEntities()
            : base("name=Ajuma_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConfigDisplayInfo> ConfigDisplayInfoes { get; set; }
        public virtual DbSet<ConfigDisplayInfoDetail> ConfigDisplayInfoDetails { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
    }
}
