//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayInfoHelper.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigDisplayInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfigDisplayInfo()
        {
            this.ConfigDisplayInfoDetails = new HashSet<ConfigDisplayInfoDetail>();
        }
    
        public long Id { get; set; }
        public string Entity { get; set; }
        public string ScreenCode { get; set; }
        public string UserType { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> Log_CreatedDate { get; set; }
        public string Log_CreatedBy { get; set; }
        public Nullable<System.DateTime> Log_UpdatedDate { get; set; }
        public string Log_UpdatedBy { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigDisplayInfoDetail> ConfigDisplayInfoDetails { get; set; }
    }
}
