//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayInfoHelper.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public long MaterialId { get; set; }
        public long GrpMaterialId { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public Nullable<long> Material_AliasId { get; set; }
        public string Material_Alias4Report { get; set; }
        public long UnitId { get; set; }
        public string Recipe { get; set; }
        public decimal PriceBeforeVAT { get; set; }
        public decimal PriceAfterVAT { get; set; }
        public decimal WholePrice { get; set; }
        public decimal SellPrice { get; set; }
        public double InventoryMax { get; set; }
        public double InventoryMin { get; set; }
        public string Account { get; set; }
        public int VIn { get; set; }
        public int VOut { get; set; }
        public string Note { get; set; }
        public decimal TimeWarranty { get; set; }
        public bool Locked { get; set; }
        public long MaterialTypeId { get; set; }
        public bool InValid { get; set; }
        public byte[] TimeStamp { get; set; }
        public decimal ProfitRateWholeSale { get; set; }
        public decimal ProfitRateRetail { get; set; }
        public byte[] TimeStampCode { get; set; }
        public string ClientCode { get; set; }
        public string SyncCode { get; set; }
        public string SeriNumber { get; set; }
        public Nullable<long> ManufactureId { get; set; }
        public Nullable<long> CountryId { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public long SupplierId { get; set; }
        public string SupplierName { get; set; }
        public Nullable<System.DateTime> Log_LastUpdate_Time_AutoByTrigger { get; set; }
        public string Log_LastUpdate_ComputerName_AutoByTrigger { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal PurchasePriceAfterVAT { get; set; }
        public int Disable { get; set; }
        public string FASH_Color { get; set; }
        public string FASH_Size { get; set; }
        public long AutoLogOnCode_LastUpdate_ById { get; set; }
        public string AutoLogOnCode_LastUpdate_ByFullName { get; set; }
        public Nullable<System.DateTime> AutoLogOnCode_LastUpdate_DateTime { get; set; }
        public string AutoLogOnCode_LastUpdate_IP { get; set; }
        public string AutoLogOnCode_LastUpdate_ComputerName { get; set; }
        public string AutoLogOnCode_LastUpdate_MACAddress { get; set; }
        public string MaterialName_Unsign { get; set; }
        public string MaterialName_Unsign_NoSpecialChar { get; set; }
        public string MaterialCode_Unsign_NoSpecialChar { get; set; }
        public long MaterialStatusId { get; set; }
        public Nullable<long> MaterialColorId { get; set; }
        public Nullable<long> MaterialDesignId { get; set; }
        public Nullable<long> MaterialSizeId { get; set; }
        public string Accounting_Number { get; set; }
        public string Accounting_SubNumber { get; set; }
        public decimal SellPriceAfterVAT { get; set; }
        public decimal WholePriceAfterVAT { get; set; }
        public Nullable<long> Config_VIn_Id { get; set; }
        public Nullable<long> Config_VOut_Id { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsBoxingType { get; set; }
        public Nullable<long> IsBoxOfMaterialId { get; set; }
        public decimal IsBoxOfMaterialId_Quantity { get; set; }
        public bool IsImportType { get; set; }
        public string MaterialName_English { get; set; }
        public string TimeStampText { get; set; }
        public string GrpMaterialCode { get; set; }
        public bool IsSystem { get; set; }
        public bool IsPaymentCard { get; set; }
        public string HSCode { get; set; }
        public Nullable<long> Config_VInImport_Id { get; set; }
        public string BatchNoCode { get; set; }
        public string SoCongBo { get; set; }
        public string KQuaPhanLoai { get; set; }
        public long Id { get; set; }
        public Nullable<System.Guid> IDGuid { get; set; }
        public decimal RateInWeb { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
